# Assignment 1 (Applied Data Science)

## Megha Nath

### 1

In [1]:
name='Megha'
age=21

In [3]:
print("Name: ",name)
print("Age: ",age)

Name:  Megha
Age:  21


### 2

In [5]:
X="Data Science is used to extract meaningful insights."
split_string=X.split()
print(split_string)

['Data', 'Science', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


### 3

In [7]:
def multiply(x,y):
    return(x*y)

In [9]:
mul=multiply(28,5)
print(mul)

140


### 4

In [10]:
dictionary={'Sikkim':'Gangtok','Tamil Nadu':'Chennai','West Bengal':'Kolkata','Maharashtra':'Mumbai','Madhya Pradesh':'Bhopal'}
print(dictionary)

{'Sikkim': 'Gangtok', 'Tamil Nadu': 'Chennai', 'West Bengal': 'Kolkata', 'Maharashtra': 'Mumbai', 'Madhya Pradesh': 'Bhopal'}


In [12]:
print(dictionary.keys())

dict_keys(['Sikkim', 'Tamil Nadu', 'West Bengal', 'Maharashtra', 'Madhya Pradesh'])


In [13]:
print(dictionary.values())

dict_values(['Gangtok', 'Chennai', 'Kolkata', 'Mumbai', 'Bhopal'])


In [15]:
for key,value in dictionary.items():
    print(key, value)

Sikkim Gangtok
Tamil Nadu Chennai
West Bengal Kolkata
Maharashtra Mumbai
Madhya Pradesh Bhopal


### 5

In [16]:
import numpy as np

In [17]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

### 6

In [19]:
id_matrix=np.identity(4,dtype=int)
print(id_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### 7

In [21]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 8

In [22]:
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(21,33).reshape(3,4)

In [26]:
result=np.array(arr1)+np.array(arr2)
print(result)

[[22 24 26 28]
 [30 32 34 36]
 [38 40 42 44]]


### 9

In [27]:
from datetime import datetime,timedelta

In [36]:
start=datetime(2023,2,1)
end=datetime(2023,3,1)

In [37]:
dates=[]
while start<=end:
    dates.append(start)
    start=start+timedelta(days=1)

In [40]:
for i in dates:
    print(i.date())

2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


### 10

In [41]:
dic1= {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
dic1

{'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales': [250, 200, 240]}

In [42]:
import pandas as pd

In [43]:
df=pd.DataFrame(dic1)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
